<?php

namespace App\Admin\Repositories\Article;

use App\Admin\Models\Article\Article;
use App\Repositories\Repository;
use Illuminate\Database\Eloquent\Model;

/**
 * Class TeMaiRepository
 * @package App\Application\TeMai\Repositories
 */
class ArticleRepository extends Repository
{
    /**
     * Associated Repository Model
     */
    const MODEL = Article::class;


    public function create(array $data){
        $articleChannel = $this->createStub($data);
        return parent::save($articleChannel);
    }

    public function update(Model $model, array $input)
    {
        return parent::update($model, $input); // TODO: Change the autogenerated stub
    }


    /**
     * @param  $input
     * @return mixed
     */
    public function createStub($input)
    {
        $articleChannel = self::MODEL;
        $articleChannel = new $articleChannel;

        $articleChannel->platform = $input['platform'];
        $articleChannel->account = $input['account'];
        $articleChannel->commodity_click = $input['commodity_click'];

        $articleChannel->date = $input['date'];
        $articleChannel->income = $input['income'];
        $articleChannel->settlement_money = $input['settlement_money'];
        $articleChannel->pay_order_count = $input['pay_order_count'];
        $articleChannel->source_type = $input['source_type'];
        return $articleChannel;
    }
}
